In [5]:
import pandas as pd

providers = pd.read_csv("providers_data.csv")

providers.head()
providers.info()
providers.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Provider_ID  1000 non-null   int64
 1   Name         1000 non-null   object
 2   Type         1000 non-null   object
 3   Address      1000 non-null   object
 4   City         1000 non-null   object
 5   Contact      1000 non-null   object
dtypes: int64(1), object(5)
memory usage: 47.0+ KB

Provider_ID    0
Name           0
Type           0
Address        0
City           0
Contact        0
dtype: int64

In [2]:
import sqlite3

conn = sqlite3.connect("database.db")

In [6]:
providers = pd.read_csv("providers_data.csv")
receivers = pd.read_csv("receivers_data.csv")
food = pd.read_csv("food_listings_data.csv")
claims = pd.read_csv("claims_data.csv")

In [8]:
claims.isnull().sum()

Claim_ID       0
Food_ID        0
Receiver_ID    0
Status         0
Timestamp      0
dtype: int64

In [9]:
providers["Type"].unique()

array(['Supermarket', 'Grocery Store', 'Restaurant', 'Catering Service'],
      dtype=object)

In [10]:
food.describe()

           Food_ID     Quantity  Provider_ID
count  1000.000000  1000.000000     1000.000
mean    500.500000    25.794000      497.497
std     288.819436    14.609894      291.681
min       1.000000     1.000000        1.000
25%     250.750000    13.000000      241.000
50%     500.500000    26.000000      498.500
75%     750.250000    39.000000      752.000
max    1000.000000    50.000000     1000.000

In [11]:
print("Providers Missing Values")
print(providers.isnull().sum())

print("\nReceivers Missing Values")
print(receivers.isnull().sum())

print("\nFood Missing Values")
print(food.isnull().sum())

print("\nClaims Missing Values")
print(claims.isnull().sum())

Providers Missing Values
Provider_ID    0
Name           0
Type           0
Address        0
City           0
Contact        0
dtype: int64

Receivers Missing Values
Receiver_ID    0
Name           0
Type           0
City           0
Contact        0
dtype: int64

Food Missing Values
Food_ID          0
Food_Name        0
Quantity         0
Expiry_Date      0
Provider_ID      0
Provider_Type    0
Location         0
Food_Type        0
Meal_Type        0
dtype: int64

Claims Missing Values
Claim_ID       0
Food_ID        0
Receiver_ID    0
Status         0
Timestamp      0
dtype: int64

In [12]:
providers_clean = providers.copy()
receivers_clean = receivers.copy()
food_clean = food.copy()
claims_clean = claims.copy()

In [13]:
providers_clean = providers_clean.drop_duplicates()
receivers_clean = receivers_clean.drop_duplicates()
food_clean = food_clean.drop_duplicates()
claims_clean = claims_clean.drop_duplicates()

In [14]:
print(providers_clean.duplicated().sum())
print(receivers_clean.duplicated().sum())
print(food_clean.duplicated().sum())
print(claims_clean.duplicated().sum())

0
0
0
0

In [16]:
providers_clean.isnull().sum()
receivers_clean.isnull().sum()
food_clean.isnull().sum()
claims_clean.isnull().sum()

Claim_ID       0
Food_ID        0
Receiver_ID    0
Status         0
Timestamp      0
dtype: int64

In [17]:
providers_clean = providers_clean.fillna("Unknown")
receivers_clean = receivers_clean.fillna("Unknown")

In [18]:
food_clean["Quantity"] = food_clean["Quantity"].fillna(0)

In [19]:
providers_clean.columns

Index(['Provider_ID', 'Name', 'Type', 'Address', 'City', 'Contact'], dtype='object')

In [20]:
providers_clean.columns = providers_clean.columns.str.strip()
receivers_clean.columns = receivers_clean.columns.str.strip()
food_clean.columns = food_clean.columns.str.strip()
claims_clean.columns = claims_clean.columns.str.strip()

In [21]:
providers_clean.dtypes
food_clean.dtypes
claims_clean.dtypes

Claim_ID        int64
Food_ID         int64
Receiver_ID     int64
Status         object
Timestamp      object
dtype: object

In [22]:
food_clean["Expiry_Date"] = pd.to_datetime(
    food_clean["Expiry_Date"]
)

In [24]:
claims_clean["Timestamp"] = pd.to_datetime(
    claims_clean["Timestamp"]
)

In [26]:
claims_clean["Claim_Date"] = pd.to_datetime(
    claims_clean["Claim_Date"]
)

KeyError: 'Claim_Date'

In [27]:
food_clean[food_clean["Quantity"] < 0]

Empty DataFrame
Columns: [Food_ID, Food_Name, Quantity, Expiry_Date, Provider_ID, Provider_Type, Location, Food_Type, Meal_Type]
Index: []

In [28]:
food_clean = food_clean[food_clean["Quantity"] >= 0]

In [29]:
providers_clean["Type"].value_counts()

Type
Supermarket         262
Grocery Store       256
Restaurant          246
Catering Service    236
Name: count, dtype: int64

In [30]:
receivers_clean["Type"].value_counts()

Type
NGO           274
Charity       263
Shelter       246
Individual    217
Name: count, dtype: int64

In [33]:
import os

os.makedirs("cleaned_data", exist_ok=True)

In [9]:
import pandas as pd

providers = pd.read_csv("providers_data.csv")
receivers = pd.read_csv("receivers_data.csv")
food = pd.read_csv("food_listings_data.csv")
claims = pd.read_csv("claims_data.csv")

In [10]:
providers_clean.to_csv(
    "cleaned_data/providers_clean.csv",
    index=False
)

receivers_clean.to_csv(
    "cleaned_data/receivers_clean.csv",
    index=False
)

food_clean.to_csv(
    "cleaned_data/food_clean.csv",
    index=False
)

claims_clean.to_csv(
    "cleaned_data/claims_clean.csv",
    index=False
)

NameError: name 'providers_clean' is not defined

In [1]:
print(providers_clean.columns.tolist())
print(receivers_clean.columns.tolist())
print(food_clean.columns.tolist())
print(claims_clean.columns.tolist())

NameError: name 'providers_clean' is not defined

In [3]:
globals().keys()

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__vsc_ipynb_file__', '_i', '_ii', '_iii', '_i1', '_i2', '_i3'])

In [4]:
print(providers.head())

NameError: name 'providers' is not defined

In [11]:
print(providers.columns.tolist())
print(receivers.columns.tolist())
print(food.columns.tolist())
print(claims.columns.tolist())

['Provider_ID', 'Name', 'Type', 'Address', 'City', 'Contact']
['Receiver_ID', 'Name', 'Type', 'City', 'Contact']
['Food_ID', 'Food_Name', 'Quantity', 'Expiry_Date', 'Provider_ID', 'Provider_Type', 'Location', 'Food_Type', 'Meal_Type']
['Claim_ID', 'Food_ID', 'Receiver_ID', 'Status', 'Timestamp']

In [12]:
pip install pymysql sqlalchemy

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.51-cp310-cp310-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.1-cp310-cp310-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\athul varma\anaconda3\envs\myenv\lib\site-packages (from sqlalchemy) (4.12.2)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Downloading sqlalchemy-2.0.51-cp310-cp310-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   -------------- ------------------------- 0.8/2.1 MB 8.3 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 5.5 MB/s eta 0:00:00
Downloading greenlet-3.5.1-cp310-cp310-win_amd64.whl (237 kB)
Installing collected packages: pymysql, greenlet, sqlalchemy
Successfully installed greenlet-3.5.1 pymysql-1.2.0 sqlalchemy-2.0.51
Note: you may need to restart the kernel to use updated packages.

In [1]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Athul%401335@localhost:3306/food_wastage_management"
)

with engine.connect() as conn:
    print("Connected Successfully")

Connected Successfully

In [15]:
import pandas as pd

providers = pd.read_csv("cleaned_data/providers_clean.csv")
receivers = pd.read_csv("cleaned_data/receivers_clean.csv")
food = pd.read_csv("cleaned_data/food_clean.csv")
claims = pd.read_csv("cleaned_data/claims_clean.csv")

In [16]:
providers.to_sql(
    "Providers",
    con=engine,
    if_exists="append",
    index=False
)

print("Providers Uploaded")

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '1335@localhost' ([Errno 11003] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [19]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Athul%401335@localhost:3306/food_wastage_management"
)

with engine.connect() as conn:
    print("Connected Successfully")

Connected Successfully

In [21]:
receivers.to_sql(
    "Receivers",
    con=engine,
    if_exists="append",
    index=False
)

print("Receivers Uploaded")

Receivers Uploaded

C:\Users\Athul Varma\AppData\Local\Temp\ipykernel_17160\789468678.py:1: UserWarning: The provided table name 'Receivers' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  receivers.to_sql(

In [22]:
providers.to_sql(
    "Providers",
    con=engine,
    if_exists="append",
    index=False
)

print("Providers Uploaded")

Providers Uploaded

C:\Users\Athul Varma\AppData\Local\Temp\ipykernel_17160\1523982226.py:1: UserWarning: The provided table name 'Providers' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  providers.to_sql(

In [23]:
claims.to_sql(
    "Claims",
    con=engine,
    if_exists="append",
    index=False
)

print("Claims Uploaded")

Claims Uploaded

C:\Users\Athul Varma\AppData\Local\Temp\ipykernel_17160\4102211096.py:1: UserWarning: The provided table name 'Claims' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  claims.to_sql(

In [24]:
food.to_sql(
    "Food_Listings",
    con=engine,
    if_exists="append",
    index=False
)

print("Food Uploaded")

Food Uploaded

C:\Users\Athul Varma\AppData\Local\Temp\ipykernel_17160\503934934.py:1: UserWarning: The provided table name 'Food_Listings' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  food.to_sql(